version: '3.8'
services:
  vfd-control:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODBUS_HOST=192.168.1.42
      - MODBUS_PORT=23
    network_mode: "host"
    restart: unless-stopped